version: 2.1

references:
  container: &container
    docker:
      # docker file .docker/build.Dockerfile
      # image pushed to inejc/semanticweights
      - image: inejc/semanticweights:tarok-build-14022020

  checkout_submodules: &checkout_submodules
    run:
      name: Checkout git submodules
      command: |
        git submodule sync
        git submodule update --init

  restore_cache: &restore_cache
    restore_cache:
      name: Restore python cache
      key: py-cache-{{ .Branch }}-{{ checksum "tarok/libs/open_spiel/requirements.txt" }}

  install_dependencies: &install_dependencies
    run:
      name: Install dependencies
      command: |
        pip3 install --upgrade pip setuptools
        pip3 install -r tarok/libs/open_spiel/requirements.txt

  build_project: &build_project
    run:
      name: Build the project
      command: ./tarok/install.sh

  run_tests: &run_tests
    run:
      name: Run the tests
      command: ./build/test/tarok_tests

  save_cache: &save_cache
    save_cache:
      name: Save python cache
      key: py-cache-{{ .Branch }}-{{ checksum "tarok/libs/open_spiel/requirements.txt" }}
      paths:
        - /usr/local/lib/python3.7/dist-packages

jobs:
  test-and-build-module:
    <<: *container
    steps:
      - checkout
      - *checkout_submodules
      - *restore_cache
      - *install_dependencies
      - *build_project
      - *run_tests
      - *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - build/src/
            - build/libs/open_spiel/open_spiel/python

  build-image-and-push:
    <<: *container
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ls build/src

workflows:
  version: 2.1
  test-build-push:
    jobs:
      - test-and-build-module
      - build-image-and-push:
          requires:
            - test-and-build-module
          filters:
            branches:
              only:
                - production
