name: continuous-integration
on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/semanticweights/tarok/tarok-build:13022020
    steps:
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: echo "building tarok"
